# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Manuel McCadden"
description: > # this means to ignore newlines until "email:"
   Estudiante de Ciencia de Datos y Matemáticas Aplicadas

email: manuel.mccaddenm@gmail.com
#blog logo
logo: "/assets/images/foto_redonda.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/foto_arriba.webp"

name: 'Manuel McCadden'
author: 'Manuel McCadden'
author_image: "/assets/images/foto_redonda.jpg"

paginate:	3

url: "https://manuelmccaddenm.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/manuel-mccadden-madrazo-404899238/
    desc: Connect with me on linkedin
    #share_url: http://twitter.com/share
    #share_title: ?text=
    #share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/manuelmccadden
    desc:	Fork me on github
    #share_url:
    #share_title:
    #share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
